version: '3'
services:
  jmfc:
    container_name: jmfc
    image: jenkinsluckev/feedback-collector:latest
    restart: always
    volumes:
      - jmfc-secrets:/var/data/secrets/jmfc
    networks:
      jenkins:
        ipv4_address: 172.16.1.221
volumes:
  jmfc-secrets:
    external: true
networks:
  default:
    external:
      name: jenkins
  jenkins:
    external: true