version: '3'
services:
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 80:80
      - 443:443
    restart: always
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /var/data/mysql/secrets/root_pass
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - jmfc-database-data:/var/lib/mysql
      - jmfc-database-secrets:/var/data/mysql/secrets
  jmfc:
    volumes:
      - ./:/var/www/html
volumes:
  jmfc-database-data:
    external: true
  jmfc-database-secrets:
    external: true
networks:
  default:
    external:
      name: jenkins
  jenkins:
    external: true