version: '3'
services:
  jmfct:
    container_name: jmfct
    image: jenkinsluckev/feedback-collector:latest
    restart: always
    environment:
      - TEAM=1
    volumes:
      - jmfct-secrets:/var/data/secrets/jmfc
    networks:
      jenkins:
        ipv4_address: 172.16.1.222
volumes:
  jmfct-secrets:
    external: true
networks:
  default:
    external:
      name: jenkins
  jenkins:
    external: true